services:
  mysql:
    image: mysql:5
    environment:
      - MYSQL_DB=microservice
      - MYSQL_ROOT_PASSWORD=grandetuco1
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=grandetuco1
      - PMA_HOST=mysql
    ports:
      - 8080:80